// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutrilab.DataAccess.Context;

#nullable disable

namespace Nutrilab.DataAccess.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20260308220318_AddCategoryAndPrepTimeFieldsOnRecipes")]
    partial class AddCategoryAndPrepTimeFieldsOnRecipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nutrilab.DataAccess.Models.FavouriteRecipes.FavouriteRecipe", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("FavouriteRecipes", (string)null);
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Ingredients.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Permissions.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "user.manage.roles"
                        },
                        new
                        {
                            Id = 2,
                            Name = "recipe.create"
                        },
                        new
                        {
                            Id = 3,
                            Name = "recipe.edit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "recipe.delete"
                        },
                        new
                        {
                            Id = 5,
                            Name = "recipe.read"
                        },
                        new
                        {
                            Id = 6,
                            Name = "recipe.favourite"
                        });
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.RecipeIngredients.RecipeIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.RecipeResources.RecipeResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeResources", (string)null);
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Recipes.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DifficultyLvl")
                        .HasColumnType("int");

                    b.Property<int?>("MealCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PreparationTimeMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.RolePermissions.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 6
                        });
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maintainer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Editor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.ShoppingListItems.ShoppingListItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("ShoppingListId")
                        .HasColumnType("bigint");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsChecked = false,
                            Name = "Piletina",
                            Quantity = 1.5m,
                            ShoppingListId = 1L,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2L,
                            IsChecked = false,
                            Name = "Brokoli",
                            Quantity = 2m,
                            ShoppingListId = 1L,
                            Unit = "kom"
                        },
                        new
                        {
                            Id = 3L,
                            IsChecked = true,
                            Name = "Maslinovo ulje",
                            Quantity = 500m,
                            ShoppingListId = 1L,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 4L,
                            IsChecked = false,
                            Name = "Ovsene pahuljice",
                            Quantity = 500m,
                            ShoppingListId = 2L,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 5L,
                            IsChecked = false,
                            Name = "Protein u prahu",
                            Quantity = 1m,
                            ShoppingListId = 2L,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.ShoppingLists.ShoppingList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ShoppingLists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedByUserId = 1L,
                            Name = "Nedeljna kupovina"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedByUserId = 4L,
                            Name = "Fitness obroci"
                        });
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.UserRoles.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2L,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3L,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4L,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@nutriplan.com",
                            PasswordHash = "$2a$11$3FxdA3t4oyB3FO.CNmY.Tem4sy3AI.//yOaJO/suHNahlRyysGE3a"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maintainer@nutriplan.com",
                            PasswordHash = "$2a$11$t58KV3nhGBV.iCCVlDo7cekNrrlpziyB5YX8GE5ZxBZg1yC3PvB8m"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "editor@nutriplan.com",
                            PasswordHash = "$2a$11$t58KV3nhGBV.iCCVlDo7cekNrrlpziyB5YX8GE5ZxBZg1yC3PvB8m"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@nutriplan.com",
                            PasswordHash = "$2a$11$t58KV3nhGBV.iCCVlDo7cekNrrlpziyB5YX8GE5ZxBZg1yC3PvB8m"
                        });
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.FavouriteRecipes.FavouriteRecipe", b =>
                {
                    b.HasOne("Nutrilab.DataAccess.Models.Recipes.Recipe", "Recipe")
                        .WithMany("FavouriteUsers")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nutrilab.DataAccess.Models.Users.User", "User")
                        .WithMany("FavouriteRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.RecipeIngredients.RecipeIngredient", b =>
                {
                    b.HasOne("Nutrilab.DataAccess.Models.Ingredients.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nutrilab.DataAccess.Models.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.RecipeResources.RecipeResource", b =>
                {
                    b.HasOne("Nutrilab.DataAccess.Models.Recipes.Recipe", "Recipe")
                        .WithMany("Resources")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Recipes.Recipe", b =>
                {
                    b.HasOne("Nutrilab.DataAccess.Models.Users.User", "CreatedByUser")
                        .WithMany("Recipes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.RolePermissions.RolePermission", b =>
                {
                    b.HasOne("Nutrilab.DataAccess.Models.Permissions.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nutrilab.DataAccess.Models.Roles.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.ShoppingListItems.ShoppingListItem", b =>
                {
                    b.HasOne("Nutrilab.DataAccess.Models.ShoppingLists.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.ShoppingLists.ShoppingList", b =>
                {
                    b.HasOne("Nutrilab.DataAccess.Models.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.UserRoles.UserRole", b =>
                {
                    b.HasOne("Nutrilab.DataAccess.Models.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nutrilab.DataAccess.Models.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Ingredients.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Permissions.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Recipes.Recipe", b =>
                {
                    b.Navigation("FavouriteUsers");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.ShoppingLists.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Nutrilab.DataAccess.Models.Users.User", b =>
                {
                    b.Navigation("FavouriteRecipes");

                    b.Navigation("Recipes");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
